# R1T1

## Openning Data

In [11]:
using MAT
using LinearAlgebra
using SparseArrays
using JuMP
using GLPK

In [9]:
file = matopen("R1T1.mat")
varnames = names(file)

3-element Array{String,1}:
 "S"
 "l1"
 "u1"

In [38]:
S = read(file, "S")
l1 = read(file, "l1")
u1 = read(file, "u1")

Dict{String,Any} with 3 entries:
  "nzval" => [0.0945981, 0.0962594, 0.00953525, 0.352967, 1.61011, 1.45645, 0.9…
  "nzind" => [2, 3, 4, 10, 14, 15, 17, 21, 27, 36  …  77, 80, 83, 84, 85, 87, 8…
  "n"     => 95

In [43]:
l1_nzval = l1["nzval"]
l1_nzind = l1["nzind"]
l1_n = l1["n"]
l = SparseVector(l1_n, l1_nzind, l1_nzval)

95-element SparseVector{Float64,Int64} with 41 stored entries:
  [1 ]  =  -0.567967
  [2 ]  =  -0.411144
  [5 ]  =  -0.324701
  [7 ]  =  -0.799832
  [23]  =  -1.20169
  [24]  =  -0.98075
  [25]  =  -2.04877
  [26]  =  -1.45278
  [28]  =  -3.52789
  [29]  =  -1.24286
        ⋮
  [75]  =  -1.67909
  [76]  =  -9.87177e-18
  [81]  =  -0.315631
  [82]  =  -1.15417
  [83]  =  -0.906035
  [86]  =  -0.881084
  [89]  =  -1.27967
  [91]  =  -1.50791
  [92]  =  0.0546867
  [94]  =  -0.643764
  [95]  =  -0.87322

In [44]:
u1_nzval = u1["nzval"]
u1_nzind = u1["nzind"]
u1_n = u1["n"]
u = SparseVector(u1_n, u1_nzind, u1_nzval)

95-element SparseVector{Float64,Int64} with 40 stored entries:
  [2 ]  =  0.0945981
  [3 ]  =  0.0962594
  [4 ]  =  0.00953525
  [10]  =  0.352967
  [14]  =  1.61011
  [15]  =  1.45645
  [17]  =  0.954616
  [21]  =  0.311844
  [27]  =  0.146057
  [36]  =  -7.21753e-18
        ⋮
  [76]  =  6.10131e-19
  [77]  =  1.26479
  [80]  =  1.3062
  [83]  =  0.77279
  [84]  =  1.63928
  [85]  =  1.78739
  [87]  =  1.0817
  [89]  =  -0.9569
  [90]  =  1.56944
  [92]  =  0.814742
  [93]  =  0.0176237

In [49]:
m,n = size(S)

(72, 95)

In [51]:
mzeros = zeros(m,1);

## Constructing  Model

In [52]:
model = Model(GLPK.Optimizer)
@variable(model,v[1:n])
@constraint(model, l .<= v)
@constraint(model, v .<= u)
@constraint(model, S*v .== mzeros)
@objective(model,Min,1)

1

In [53]:
optimize!(model)

In [54]:
@show termination_status(model)
@show primal_status(model)
@show dual_status(model)
@show objective_value(model)
@show JuMP.value.(v)

termination_status(model) = MathOptInterface.OPTIMAL
primal_status(model) = MathOptInterface.FEASIBLE_POINT
dual_status(model) = MathOptInterface.FEASIBLE_POINT
objective_value(model) = 1.0
JuMP.value.(v) = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.10937336742125003, -0.10937336742125003, -0.9569002300321277, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.38616393690226897, -0.38616393690226897, 0.0, -0.33147725319164395, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -0.9569002300321277, 0.0, 0.0, 0.05468668371062502, 0.0, 0.0, 0.0]


95-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.9569002300321277
  0.0
  0.0
  0.05468668371062502
  0.0
  0.0
  0.0

In [55]:
v = JuMP.value.(v)

95-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0
  0.0
  0.0
 -0.9569002300321277
  0.0
  0.0
  0.05468668371062502
  0.0
  0.0
  0.0

## writing to putput file

In [60]:
using DelimitedFiles
open("output.txt","w") do io
    writedlm(io, v)
end