# R1T2

## Openning Data

In [1]:
using MAT
using LinearAlgebra
using SparseArrays
using JuMP
using GLPK

In [3]:
file = matopen("R1T2.mat")
varnames = names(file)

3-element Array{String,1}:
 "S"
 "l1"
 "u1"

In [4]:
S = read(file, "S")
l1 = read(file, "l1")
u1 = read(file, "u1")

Dict{String,Any} with 3 entries:
  "nzval" => [-1.46586e-17, 0.800147, 0.506678, -1.10494e-16, 8.4613e-17, 0.204…
  "nzind" => [4, 5, 24, 28, 36, 43, 49, 50, 64, 69  …  3275, 3278, 3289, 3297, …
  "n"     => 3357

In [5]:
l1_nzval = l1["nzval"]
l1_nzind = l1["nzind"]
l1_n = l1["n"]
l = SparseVector(l1_n, l1_nzind, l1_nzval)

3357-element SparseVector{Float64,Int64} with 285 stored entries:
  [1   ]  =  -0.430798
  [4   ]  =  -2.93727e-17
  [28  ]  =  -2.36424e-16
  [36  ]  =  -9.79702e-17
  [40  ]  =  -0.456247
  [49  ]  =  2.75983e-18
  [50  ]  =  -6.97551e-17
  [55  ]  =  -2.07778
  [63  ]  =  -0.803578
  [74  ]  =  5.34225e-18
          ⋮
  [3227]  =  -1.26776
  [3260]  =  -0.988011
  [3266]  =  -0.615081
  [3270]  =  -5.90159e-18
  [3275]  =  9.67206e-18
  [3285]  =  -0.108682
  [3293]  =  -0.420411
  [3294]  =  -0.71665
  [3297]  =  7.13642e-18
  [3308]  =  -0.56776
  [3338]  =  -1.18314

In [6]:
u1_nzval = u1["nzval"]
u1_nzind = u1["nzind"]
u1_n = u1["n"]
u = SparseVector(u1_n, u1_nzind, u1_nzval)

3357-element SparseVector{Float64,Int64} with 260 stored entries:
  [4   ]  =  -1.46586e-17
  [5   ]  =  0.800147
  [24  ]  =  0.506678
  [28  ]  =  -1.10494e-16
  [36  ]  =  8.4613e-17
  [43  ]  =  0.20423
  [49  ]  =  3.96795e-18
  [50  ]  =  -4.33363e-17
  [64  ]  =  1.02999
  [69  ]  =  0.879655
          ⋮
  [3270]  =  -9.80482e-19
  [3275]  =  2.89753e-17
  [3278]  =  1.32765
  [3289]  =  1.06546
  [3297]  =  1.7007e-17
  [3303]  =  1.74757
  [3311]  =  0.589217
  [3314]  =  0.00415554
  [3334]  =  0.0909567
  [3344]  =  1.41846
  [3347]  =  1.72875

In [7]:
m,n = size(S)

(2436, 3357)

In [8]:
mzeros = zeros(m,1);

# Constructing  Model

In [9]:
model = Model(GLPK.Optimizer)
@variable(model,v[1:n])
@constraint(model, l .<= v)
@constraint(model, v .<= u)
@constraint(model, S*v .== mzeros)
@objective(model,Min,1)

1

In [10]:
optimize!(model)

In [11]:
@show termination_status(model)
@show primal_status(model)
@show dual_status(model)
@show objective_value(model)
@show JuMP.value.(v)

termination_status(model) = MathOptInterface.OPTIMAL
primal_status(model) = MathOptInterface.FEASIBLE_POINT
dual_status(model) = MathOptInterface.FEASIBLE_POINT
objective_value(model) = 1.0
JuMP.value.(v) = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.8164551288834814e-18, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.620263296296495e-23, 3.620263296296495e-23, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -2.5330651442790178e-18, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0722802537601777, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 

3357-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [12]:
v = JuMP.value.(v)

3357-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

# writing to output file

In [13]:
using DelimitedFiles
open("output.txt","w") do io
    writedlm(io, v)
end