# R1T3

# Openning Data

In [1]:
using MAT
using LinearAlgebra
using SparseArrays
using JuMP
using GLPK

In [2]:
file = matopen("R1T3.mat")
varnames = names(file)

3-element Array{String,1}:
 "S"
 "l1"
 "u1"

In [3]:
S = read(file, "S")
l1 = read(file, "l1")
u1 = read(file, "u1")

Dict{String,Any} with 3 entries:
  "nzval" => [0.536369, 0.728394, 0.0183641, 1.20206e-16, 6.88938e-18, 0.403529…
  "nzind" => [25, 26, 39, 45, 67, 90, 97, 104, 105, 106  …  6492, 6540, 6570, 6…
  "n"     => 6663

In [4]:
l1_nzval = l1["nzval"]
l1_nzind = l1["nzind"]
l1_n = l1["n"]
l = SparseVector(l1_n, l1_nzind, l1_nzval)

6663-element SparseVector{Float64,Int64} with 612 stored entries:
  [16  ]  =  -0.492217
  [30  ]  =  -0.938267
  [44  ]  =  -0.510348
  [45  ]  =  7.43348e-17
  [57  ]  =  -1.67201
  [64  ]  =  -0.180278
  [67  ]  =  -1.13148e-17
  [107 ]  =  -0.778074
  [122 ]  =  -0.926254
  [125 ]  =  -1.52276
          ⋮
  [6570]  =  1.40655e-17
  [6572]  =  -1.67112
  [6598]  =  -0.748896
  [6599]  =  -1.9726
  [6611]  =  0.324654
  [6614]  =  -1.16267
  [6616]  =  -0.742368
  [6619]  =  -0.767316
  [6640]  =  1.01255e-17
  [6649]  =  -0.769113
  [6662]  =  -6.97678e-17

In [5]:
u1_nzval = u1["nzval"]
u1_nzind = u1["nzind"]
u1_n = u1["n"]
u = SparseVector(u1_n, u1_nzind, u1_nzval)

6663-element SparseVector{Float64,Int64} with 582 stored entries:
  [25  ]  =  0.536369
  [26  ]  =  0.728394
  [39  ]  =  0.0183641
  [45  ]  =  1.20206e-16
  [67  ]  =  6.88938e-18
  [90  ]  =  0.403529
  [97  ]  =  0.257161
  [104 ]  =  1.29304
  [105 ]  =  0.763484
  [106 ]  =  0.414553
          ⋮
  [6491]  =  1.859
  [6492]  =  1.0017
  [6540]  =  0.383018
  [6570]  =  1.69302e-17
  [6572]  =  1.13701
  [6573]  =  0.622149
  [6576]  =  0.316024
  [6611]  =  1.45654
  [6637]  =  0.0244206
  [6640]  =  2.70448e-17
  [6662]  =  -1.34662e-18

In [6]:
m,n = size(S)

(4456, 6663)

In [7]:
mzeros = zeros(m,1);

# Constructing  Model

In [8]:
model = Model(GLPK.Optimizer)
@variable(model,v[1:n])
@constraint(model, l .<= v)
@constraint(model, v .<= u)
@constraint(model, S*v .== mzeros)
@objective(model,Min,1)

1

In [9]:
optimize!(model)

In [10]:
@show termination_status(model)
@show primal_status(model)
@show dual_status(model)
@show objective_value(model)
@show JuMP.value.(v)

termination_status(model) = MathOptInterface.OPTIMAL
primal_status(model) = MathOptInterface.FEASIBLE_POINT
dual_status(model) = MathOptInterface.FEASIBLE_POINT
objective_value(model) = 1.0
JuMP.value.(v) = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2508875783968012e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -5.866661429013584e-18, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -5.866661429013584e-18, -5.866661429013584e-18, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2508875783968012e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -3.4401303019061966e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1288770647957381e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -3.251381837279488e-17, 0.0, 0.0, 0.

6663-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [11]:
v = JuMP.value.(v)

6663-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

# writing to output file

In [12]:
using DelimitedFiles
open("output.txt","w") do io
    writedlm(io, v)
end